### ISSUE TITLE
full version run fit_generator failed

### ISSUE THREAD

**Issue by broadwit** [emilwallner/Coloring-greyscale-images#12]
env: tensorflow-gpu 1.15.0，keras 2.3.1，cudakit 10.0.130，cudann 7.6.5

when run full version, encountered following problems, try global_variables_initializer, can't resolve:
2020-04-25 20:43:26.316669: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
Traceback (most recent call last):
  File "D:/work/py/Coloring-greyscale-images/Full-version/full_version.py", line 112, in <module>
    model.fit_generator(image_a_b_gen(batch_size), epochs=1, steps_per_epoch=1)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\engine\training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\utils\data_utils.py", line 742, in get
    six.reraise(*sys.exc_info())
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\utils\data_utils.py", line 711, in get
    inputs = future.get(timeout=30)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\utils\data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "D:/work/py/Coloring-greyscale-images/Full-version/full_version.py", line 97, in image_a_b_gen
    embed = create_inception_embedding(grayscaled_rgb)
  File "D:/work/py/Coloring-greyscale-images/Full-version/full_version.py", line 81, in create_inception_embedding
    embed = inception.predict(grayscaled_rgb_resized)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\engine\training.py", line 1462, in predict
    callbacks=callbacks)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\keras\engine\training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tf1_gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable batch_normalization_177/beta from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/batch_normalization_177/beta)
	 [[{{node batch_normalization_177/cond/ReadVariableOp}}]]
	 [[predictions/Softmax/_7]]
  (1) Failed precondition: Error while reading resource variable batch_normalization_177/beta from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/batch_normalization_177/beta)
	 [[{{node batch_normalization_177/cond/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.

**Comment by broadwit** [comment]
Alpha and beta version can work normally in the same enviroment.

In the full version, if I replaced the following code in create_inception_embedding function ,the code could continue to run.
    with inception.graph.as_default():
        embed = inception.predict(grayscaled_rgb_resized)

But, I tested the create_inception_embedding function with a single input tensor, it could work.

**Comment by broadwit** [comment]
I have changed to tensorflow 2.1 env, and it's ok now.

**Comment by broadwit** [comment]
But I don't know why the problems above occurred yet...

**Comment by rubyruins** [comment]
@broadwit I think you will have to call .fit, instead of .fit_generator for tensorflow 2

**Comment by jeanpierrefakhry** [comment]
@broadwit can you please send the code that you changed? 
I'm stuck on the same issue

**Comment by Maitreya-Stark** [comment]
Sorry wrong user here...

**Comment by jeanpierrefakhry** [comment]
What @Maitreya-Stark ? i didn't really understand what you said

**Comment by GreihMurray** [comment]
> Alpha and beta version can work normally in the same enviroment.
> 
> In the full version, if I replaced the following code in create_inception_embedding function ,the code could continue to run. with inception.graph.as_default(): embed = inception.predict(grayscaled_rgb_resized)
> 
> But, I tested the create_inception_embedding function with a single input tensor, it could work.

What did you change it too @broadwit ? Im having the same issue

**Comment by jeanpierrefakhry** [comment]
@GreihMurray I solved this issue by replacing 
```
inception = InceptionResNetV2(weights='imagenet', include_top=True)
inception.graph = tf.get_default_graph()
```

with 

```
graph = tf.Graph()
with graph.as_default():
    sess = tf.compat.v1.Session(graph=graph)
    with sess.as_default():
        inception = InceptionResNetV2(weights='imagenet', include_top=True)
        inception.graph = tf.compat.v1.get_default_graph()
```

Hope that helps!

**Comment by GreihMurray** [comment]
@jeanpierrefakhry hey thanks for the reply, just to be clear, is that running with the up to date versions of tenserflow and keras?

**Comment by jeanpierrefakhry** [comment]
@GreihMurray tensorflow 2.1.0

**Comment by GreihMurray** [comment]
Awesome, thank you

**Comment by Uttejreddy0496** [comment]
> @jeanpierrefakhry what was the verison for keras you have used? Thanks
