### ISSUE TITLE
Exception after the previous fix

### ISSUE THREAD

**Issue by Sriteja07** [emilwallner/Coloring-greyscale-images#9]
It says "cannot pickle generator objects"

**Comment by Sriteja07** [comment]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\srite\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\srite\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\srite\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\srite\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in <lambda>
    initargs=(seqs, self.random_seed))
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\pool.py", line 175, in __init__
    self._repopulate_pool()
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\srite\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects


I keep on getting this exception even after the fix.

**Comment by emilwallner** [comment]
Hey, I made some small tweaks. I created a fresh Colab notebook, and it runs if you put the below in a cell an run it: 

`!git clone https://github.com/emilwallner/Coloring-greyscale-images && cd Coloring-greyscale-images/GAN-version/ && python3 colorize_base.py`
